site_name: Piplus_Ar
repo_name: GitHub
repo_url: https://github.com/sungbinoh/ProtoDUNE_pion_Ar_SIM_study
edit_uri: edit/102x/docs

nav:
        - Home: index.md
        - SR1:
          - "Residual mass cut": SR1/residual_mass.md
          - "Q square": SR1/Q_square.md
          - "Plots with mX cut": SR1/Plots_after_residual_mass_cut.md
theme:
        name: cinder
        include_sidebar: true
        highlightjs: true

extra_css:
  - "mystyle.css"

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
        - pymdownx.arithmatex
        - pymdownx.details
        - admonition

plugins:
    - search
    - img2fig