LIBRARY = Analyzers
OBJDIR = obj
DEPDIR = $(OBJDIR)/dep
SRCDIR = src
INCDIR = include
ADDITIONAL_ROOTMAPLIBRARY = -rml libAnalyzerTools.so -rml libDataFormats.so -rml libTree.so

include $(PDStudy_WD)/makefile.common

INCLUDES += -I$(PDStudy_WD)/DataFormats/include/
INCLUDES += -I$(PDStudy_WD)/AnalyzerTools/include/
